In [2]:
import pandas as pd
import ast

original_data = pd.read_csv('/home/s6moakba/InstructABSA/Dataset/Benchmarks/SemEval14/Train/Restaurants_Train.csv')
original_data.head()

,sentenceId,raw_text,aspectTerms,aspectCategories
0,3121,But the staff was so horrible to us.,"[{'term': 'staff', 'polarity': 'negative'}]","[{'category': 'service', 'polarity': 'negative'}]"
1,2777,"To be completely fair, the only redeeming fact...","[{'term': 'food', 'polarity': 'positive'}]","[{'category': 'food', 'polarity': 'positive'},..."
2,1634,"The food is uniformly exceptional, with a very...","[{'term': 'food', 'polarity': 'positive'}, {'t...","[{'category': 'food', 'polarity': 'positive'}]"
3,2534,Where Gabriela personaly greets you and recomm...,"[{'term': 'noaspectterm', 'polarity': 'none'}]","[{'category': 'service', 'polarity': 'positive'}]"
4,583,"For those that go once and don't enjoy it, all...","[{'term': 'noaspectterm', 'polarity': 'none'}]","[{'category': 'anecdotes/miscellaneous', 'pola..."

In [3]:
gen_data = pd.read_csv('/home/s6moakba/Thesis/Data_Generation/Prompting/data/test.csv')

In [4]:
gen_data

,Terms,Polarity,prompt,text,sentence
0,"cafe,Southern Indian cuisine,Pad See Ew","negative,negative,positive",\n You are a critic who can gen...,"content=""The cafe had poor service and the Sou...",The cafe had poor service and the Southern Ind...
1,"selection of meats and seafoods,Cantonese,menu...","negative,negative,positive",\n You are a critic who can gen...,"content=""The selection of meats and seafood wa...",The selection of meats and seafood was disappo...

In [20]:
gen_data.columns.tolist()

['sentence', 'Terms', 'Polarity']

In [5]:
gen_data['Terms'] = gen_data['Terms'].apply(lambda x: x.split(','))
gen_data['Polarity'] = gen_data['Polarity'].apply(lambda x: x.split(','))

In [ ]:
# def process_terms(terms):
#     terms_list = terms[1:-1].split(', ')
#     terms_list = [item[1:-1].replace("\\", "") for item in terms_list]
#     return terms_list

In [ ]:
# gen_data['Terms'] = gen_data['Terms'].apply(process_terms)
# gen_data['Polarity'] = gen_data['Polarity'].apply(process_terms)

In [7]:
gen_data['sentence'] = gen_data['sentence'].apply(lambda x: x if isinstance(x, str) else '.')

In [8]:
gen_data

,Terms,Polarity,prompt,text,sentence
0,"[cafe, Southern Indian cuisine, Pad See Ew]","[negative, negative, positive]",\n You are a critic who can gen...,"content=""The cafe had poor service and the Sou...",The cafe had poor service and the Southern Ind...
1,"[selection of meats and seafoods, Cantonese, m...","[negative, negative, positive]",\n You are a critic who can gen...,"content=""The selection of meats and seafood wa...",The selection of meats and seafood was disappo...

# filter rows that do not contain Terms

In [ ]:
# def filter_rows(row):
#     aspects = row['Terms']
#     if all(aspect in row['sentence'] for aspect in aspects):
#         row['correct'] = True    
#     else:
#         row['correct'] = False
#     return row

# gen_data = gen_data.apply(filter_rows, axis=1)

In [ ]:
# gen_data_filtered = gen_data[gen_data['correct'] == True]
# gen_data_filtered.shape

(5293, 4)

In [ ]:
# gen_data_filtered = gen_data_filtered.drop(columns=['correct'])

In [9]:
def create_aspect_terms(aspect,polarity):
    aspect_terms = []
    for aspect, polarity in zip(aspect, polarity):
        aspect_terms.append({'term': aspect, 'polarity': polarity})
    return aspect_terms

In [ ]:
# gen_data_filtered['aspectTerms'] = gen_data_filtered.apply(lambda x: create_aspect_terms(x['Terms'],x['Polarity']),axis=1)

In [10]:
gen_data['aspectTerms'] = gen_data.apply(lambda x: create_aspect_terms(x['Terms'],x['Polarity']),axis=1)

In [ ]:
# gen_data_filtered.rename(columns={'sentence':'raw_text'},inplace=True)

In [ ]:
# gen_data_filtered['aspectCategories'] = gen_data_filtered['aspectTerms'].apply(lambda x: [{'category': 'general', 'polarity': 'neutral'}])

In [ ]:
# gen_data_filtered['sentenceId'] = gen_data_filtered.index

In [11]:
gen_data

,Terms,Polarity,prompt,text,sentence,aspectTerms
0,"[cafe, Southern Indian cuisine, Pad See Ew]","[negative, negative, positive]",\n You are a critic who can gen...,"content=""The cafe had poor service and the Sou...",The cafe had poor service and the Southern Ind...,"[{'term': 'cafe', 'polarity': 'negative'}, {'t..."
1,"[selection of meats and seafoods, Cantonese, m...","[negative, negative, positive]",\n You are a critic who can gen...,"content=""The selection of meats and seafood wa...",The selection of meats and seafood was disappo...,"[{'term': 'selection of meats and seafoods', '..."

In [12]:
gen_data.rename(columns={'sentence':'raw_text'},inplace=True)
gen_data['aspectCategories'] = gen_data['aspectTerms'].apply(lambda x: [{'category': 'general', 'polarity': 'neutral'}])
gen_data.drop(columns=['text','prompt'], inplace=True)
gen_data['sentenceId'] = gen_data.index

In [13]:
gen_data

,Terms,Polarity,raw_text,aspectTerms,aspectCategories,sentenceId
0,"[cafe, Southern Indian cuisine, Pad See Ew]","[negative, negative, positive]",The cafe had poor service and the Southern Ind...,"[{'term': 'cafe', 'polarity': 'negative'}, {'t...","[{'category': 'general', 'polarity': 'neutral'}]",0
1,"[selection of meats and seafoods, Cantonese, m...","[negative, negative, positive]",The selection of meats and seafood was disappo...,"[{'term': 'selection of meats and seafoods', '...","[{'category': 'general', 'polarity': 'neutral'}]",1

In [ ]:
path = '/home/s6moakba/InstructABSA/Dataset/AUG/14_l/prompting_14_l_5k.csv'
gen_data.to_csv(path, index=False)