In [17]:
import pandas as pd
import ast

original_data = pd.read_csv('/home/s6moakba/InstructABSA/Dataset/Benchmarks/SemEval14/Train/Restaurants_Train.csv')
original_data.head()

,sentenceId,raw_text,aspectTerms,aspectCategories
0,3121,But the staff was so horrible to us.,"[{'term': 'staff', 'polarity': 'negative'}]","[{'category': 'service', 'polarity': 'negative'}]"
1,2777,"To be completely fair, the only redeeming fact...","[{'term': 'food', 'polarity': 'positive'}]","[{'category': 'food', 'polarity': 'positive'},..."
2,1634,"The food is uniformly exceptional, with a very...","[{'term': 'food', 'polarity': 'positive'}, {'t...","[{'category': 'food', 'polarity': 'positive'}]"
3,2534,Where Gabriela personaly greets you and recomm...,"[{'term': 'noaspectterm', 'polarity': 'none'}]","[{'category': 'service', 'polarity': 'positive'}]"
4,583,"For those that go once and don't enjoy it, all...","[{'term': 'noaspectterm', 'polarity': 'none'}]","[{'category': 'anecdotes/miscellaneous', 'pola..."

In [18]:
gen_data = pd.read_csv('/home/s6moakba/Thesis/agent_practice/approved_qwen_14_l.csv')

In [19]:
gen_data

,sentence,Terms,Polarity
0,The laptop starts up slowly and the 18-inch sc...,"['18-inch', 'starts', 'USB wireless card']","['negative', 'negative', 'negative']"
1,"iChat makes zooming a breeze, making it super ...","['iChat', 'zooming']","['positive', 'positive']"
2,This laptop has a switchable graphic card that...,['switchable graphic card'],['positive']
3,"The equipment at the depot is well-maintained,...","['equipment', 'depot', 'pad']","['positive', 'negative', 'negative']"
4,The laptop boasts an impressive screen/video r...,"['screen', 'video resolution']",['positive']
...,...,...,...
5395,The laptop’s AC power port is frustratingly un...,"['AC power port', 'IT support technicians', 'D...","['negative', 'negative', 'negative']"
5396,The organization of the desktop icons facilita...,['desktop icons'],['positive']
5397,The headphones provided with the laptop offer ...,['headphones'],['positive']
5398,"The laptop’s AC plug is easy to use, and the d...","['AC plug', 'driver']","['positive', 'neutral']"
5399,The 17 inch screen is perfect for all my work ...,['17 inch screen'],['positive']

In [20]:
gen_data.columns.tolist()

['sentence', 'Terms', 'Polarity']

In [ ]:
# gen_data['Terms'] = gen_data['Terms'].apply(lambda x: x.split(','))
# gen_data['Polarity'] = gen_data['Polarity'].apply(lambda x: x.split(','))

In [21]:
def process_terms(terms):
    terms_list = terms[1:-1].split(', ')
    terms_list = [item[1:-1].replace("\\", "") for item in terms_list]
    return terms_list

In [22]:
gen_data['Terms'] = gen_data['Terms'].apply(process_terms)
gen_data['Polarity'] = gen_data['Polarity'].apply(process_terms)

In [23]:
gen_data['sentence'] = gen_data['sentence'].apply(lambda x: x if isinstance(x, str) else '.')

In [24]:
gen_data

,sentence,Terms,Polarity
0,The laptop starts up slowly and the 18-inch sc...,"[18-inch, starts, USB wireless card]","[negative, negative, negative]"
1,"iChat makes zooming a breeze, making it super ...","[iChat, zooming]","[positive, positive]"
2,This laptop has a switchable graphic card that...,[switchable graphic card],[positive]
3,"The equipment at the depot is well-maintained,...","[equipment, depot, pad]","[positive, negative, negative]"
4,The laptop boasts an impressive screen/video r...,"[screen, video resolution]",[positive]
...,...,...,...
5395,The laptop’s AC power port is frustratingly un...,"[AC power port, IT support technicians, DVD dr...","[negative, negative, negative]"
5396,The organization of the desktop icons facilita...,[desktop icons],[positive]
5397,The headphones provided with the laptop offer ...,[headphones],[positive]
5398,"The laptop’s AC plug is easy to use, and the d...","[AC plug, driver]","[positive, neutral]"
5399,The 17 inch screen is perfect for all my work ...,[17 inch screen],[positive]

# filter rows that do not contain Terms

In [ ]:
# def filter_rows(row):
#     aspects = row['Terms']
#     if all(aspect in row['sentence'] for aspect in aspects):
#         row['correct'] = True    
#     else:
#         row['correct'] = False
#     return row

# gen_data = gen_data.apply(filter_rows, axis=1)

In [ ]:
# gen_data_filtered = gen_data[gen_data['correct'] == True]
# gen_data_filtered.shape

(5293, 4)

In [ ]:
# gen_data_filtered = gen_data_filtered.drop(columns=['correct'])

In [25]:
def create_aspect_terms(aspect,polarity):
    aspect_terms = []
    for aspect, polarity in zip(aspect, polarity):
        aspect_terms.append({'term': aspect, 'polarity': polarity})
    return aspect_terms

In [52]:
gen_data_filtered['aspectTerms'] = gen_data_filtered.apply(lambda x: create_aspect_terms(x['Terms'],x['Polarity']),axis=1)

In [26]:
gen_data['aspectTerms'] = gen_data.apply(lambda x: create_aspect_terms(x['Terms'],x['Polarity']),axis=1)

In [ ]:
# gen_data_filtered.rename(columns={'sentence':'raw_text'},inplace=True)

In [ ]:
# gen_data_filtered['aspectCategories'] = gen_data_filtered['aspectTerms'].apply(lambda x: [{'category': 'general', 'polarity': 'neutral'}])

In [ ]:
# gen_data_filtered['sentenceId'] = gen_data_filtered.index

In [27]:
gen_data

,sentence,Terms,Polarity,aspectTerms
0,The laptop starts up slowly and the 18-inch sc...,"[18-inch, starts, USB wireless card]","[negative, negative, negative]","[{'term': '18-inch', 'polarity': 'negative'}, ..."
1,"iChat makes zooming a breeze, making it super ...","[iChat, zooming]","[positive, positive]","[{'term': 'iChat', 'polarity': 'positive'}, {'..."
2,This laptop has a switchable graphic card that...,[switchable graphic card],[positive],"[{'term': 'switchable graphic card', 'polarity..."
3,"The equipment at the depot is well-maintained,...","[equipment, depot, pad]","[positive, negative, negative]","[{'term': 'equipment', 'polarity': 'positive'}..."
4,The laptop boasts an impressive screen/video r...,"[screen, video resolution]",[positive],"[{'term': 'screen', 'polarity': 'positive'}]"
...,...,...,...,...
5395,The laptop’s AC power port is frustratingly un...,"[AC power port, IT support technicians, DVD dr...","[negative, negative, negative]","[{'term': 'AC power port', 'polarity': 'negati..."
5396,The organization of the desktop icons facilita...,[desktop icons],[positive],"[{'term': 'desktop icons', 'polarity': 'positi..."
5397,The headphones provided with the laptop offer ...,[headphones],[positive],"[{'term': 'headphones', 'polarity': 'positive'}]"
5398,"The laptop’s AC plug is easy to use, and the d...","[AC plug, driver]","[positive, neutral]","[{'term': 'AC plug', 'polarity': 'positive'}, ..."
5399,The 17 inch screen is perfect for all my work ...,[17 inch screen],[positive],"[{'term': '17 inch screen', 'polarity': 'posit..."

In [28]:
gen_data.rename(columns={'sentence':'raw_text'},inplace=True)
gen_data['aspectCategories'] = gen_data['aspectTerms'].apply(lambda x: [{'category': 'general', 'polarity': 'neutral'}])
# gen_data.drop(columns=['text','prompt'], inplace=True)
gen_data['sentenceId'] = gen_data.index

In [29]:
gen_data

,raw_text,Terms,Polarity,aspectTerms,aspectCategories,sentenceId
0,The laptop starts up slowly and the 18-inch sc...,"[18-inch, starts, USB wireless card]","[negative, negative, negative]","[{'term': '18-inch', 'polarity': 'negative'}, ...","[{'category': 'general', 'polarity': 'neutral'}]",0
1,"iChat makes zooming a breeze, making it super ...","[iChat, zooming]","[positive, positive]","[{'term': 'iChat', 'polarity': 'positive'}, {'...","[{'category': 'general', 'polarity': 'neutral'}]",1
2,This laptop has a switchable graphic card that...,[switchable graphic card],[positive],"[{'term': 'switchable graphic card', 'polarity...","[{'category': 'general', 'polarity': 'neutral'}]",2
3,"The equipment at the depot is well-maintained,...","[equipment, depot, pad]","[positive, negative, negative]","[{'term': 'equipment', 'polarity': 'positive'}...","[{'category': 'general', 'polarity': 'neutral'}]",3
4,The laptop boasts an impressive screen/video r...,"[screen, video resolution]",[positive],"[{'term': 'screen', 'polarity': 'positive'}]","[{'category': 'general', 'polarity': 'neutral'}]",4
...,...,...,...,...,...,...
5395,The laptop’s AC power port is frustratingly un...,"[AC power port, IT support technicians, DVD dr...","[negative, negative, negative]","[{'term': 'AC power port', 'polarity': 'negati...","[{'category': 'general', 'polarity': 'neutral'}]",5395
5396,The organization of the desktop icons facilita...,[desktop icons],[positive],"[{'term': 'desktop icons', 'polarity': 'positi...","[{'category': 'general', 'polarity': 'neutral'}]",5396
5397,The headphones provided with the laptop offer ...,[headphones],[positive],"[{'term': 'headphones', 'polarity': 'positive'}]","[{'category': 'general', 'polarity': 'neutral'}]",5397
5398,"The laptop’s AC plug is easy to use, and the d...","[AC plug, driver]","[positive, neutral]","[{'term': 'AC plug', 'polarity': 'positive'}, ...","[{'category': 'general', 'polarity': 'neutral'}]",5398
5399,The 17 inch screen is perfect for all my work ...,[17 inch screen],[positive],"[{'term': '17 inch screen', 'polarity': 'posit...","[{'category': 'general', 'polarity': 'neutral'}]",5399

In [ ]:
path = '/home/s6moakba/InstructABSA/Dataset/AUG/14_l/prompting_14_l_5k.csv'
gen_data.to_csv(path, index=False)