In [2]:
import pandas as pd 

gen_data = pd.read_csv('/home/s6moakba/OLD_FILES/gen_train_16_20k.csv')

# df_2 = pd.read_csv('/home/s6moakba/Instruct_Restaurants.csv')

In [3]:
original_data = pd.read_csv('/home/s6moakba/InstructABSA/Dataset/SemEval14/Train/Restaurants_Train.csv')
original_data.head()

,sentenceId,raw_text,aspectTerms,aspectCategories
0,3121,But the staff was so horrible to us.,"[{'term': 'staff', 'polarity': 'negative'}]","[{'category': 'service', 'polarity': 'negative'}]"
1,2777,"To be completely fair, the only redeeming fact...","[{'term': 'food', 'polarity': 'positive'}]","[{'category': 'food', 'polarity': 'positive'},..."
2,1634,"The food is uniformly exceptional, with a very...","[{'term': 'food', 'polarity': 'positive'}, {'t...","[{'category': 'food', 'polarity': 'positive'}]"
3,2534,Where Gabriela personaly greets you and recomm...,"[{'term': 'noaspectterm', 'polarity': 'none'}]","[{'category': 'service', 'polarity': 'positive'}]"
4,583,"For those that go once and don't enjoy it, all...","[{'term': 'noaspectterm', 'polarity': 'none'}]","[{'category': 'anecdotes/miscellaneous', 'pola..."

In [4]:
original_data['aspectTerms'].iloc[2]

"[{'term': 'food', 'polarity': 'positive'}, {'term': 'kitchen', 'polarity': 'positive'}, {'term': 'menu', 'polarity': 'neutral'}]"

In [6]:
gen_data['aspect'] = gen_data['aspect'].str.split(',')
gen_data['polarity'] = gen_data['polarity'].str.split(',')

In [7]:
row = gen_data.iloc[3800]
print(row['aspect'])
print(row['polarity'])
print(row['generated_text'])

['chicken vindaloo']
['Negative']
The chicken vindaloo was a letdown due to its lack of flavor.

# filtering based on intended aspect present in generated Text

In [8]:
gen_data

,aspect,polarity,prompt,generated_text
0,[caviar],[Negative],You are a critic who can generate comments on ...,The caviar served at this restaurant was overp...
1,[vitello alla marsala],[Negative],You are a critic who can generate comments on ...,The vitello alla marsala was a disappointing d...
2,[bar scene],[Positive],You are a critic who can generate comments on ...,The bar scene is always lively and fun to be a...
3,[atmoshpere],[Negative],You are a critic who can generate comments on ...,The atmosphere in the restaurant was completel...
4,[seats],[Positive],You are a critic who can generate comments on ...,The seats were incredibly comfortable and prov...
...,...,...,...,...
21495,"[Zucchero Pomodori, bagel, hummus, Leon]","[Negative, Positive, Positive, Neutral]",You are a critic who can generate comments on ...,"The Zucchero Pomodori was a letdown, but the b..."
21496,"[dosas, Pastis, dining room, chicken vindaloo]","[Positive, Negative, Negative, Positive]",You are a critic who can generate comments on ...,"The dosas were absolutely delicious, but unfor..."
21497,"[half/half pizza, lunch buffet, chicken tikka ...","[Neutral, Positive, Positive, Negative]",You are a critic who can generate comments on ...,"The lunch buffet was quite impressive, the chi..."
21498,"[Rao's, fish, lobster sandwich, jukebox]","[Neutral, Positive, Negative, Positive]",You are a critic who can generate comments on ...,The service at Rao's was neutral but the fish ...
21499,"[meat, fusion twists, BBQ Salmon, sauces]","[Neutral, Negative, Negative, Positive]",You are a critic who can generate comments on ...,"The meat was average, the fusion twists didn't..."

In [9]:
def filter_rows(row):
    aspects = row['aspect']
    if all(aspect in row['generated_text'] for aspect in aspects):
        row['correct'] = True    
    else:
        row['correct'] = False
    return row

gen_data = gen_data.apply(filter_rows, axis=1)

In [10]:
gen_data = gen_data[gen_data['correct'] == True]

In [11]:
gen_data.shape

(10842, 5)

In [12]:
gen_data = gen_data.drop(columns=['correct'])

In [24]:
def create_aspect_terms(aspect,polarity):
    aspect_terms = []
    for aspect, polarity in zip(aspect, polarity):
        aspect_terms.append({'term': aspect, 'polarity': polarity})
    return aspect_terms

In [25]:
gen_data['aspectTerms'] = gen_data.apply(lambda x: create_aspect_terms(x['aspect'],x['polarity']),axis=1)

In [26]:
print(gen_data['aspectTerms'].iloc[6000])
print(gen_data['generated_text'].iloc[6000])

[{'term': 'Vanison', 'polarity': 'Negative'}, {'term': 'Big Wong', 'polarity': 'Neutral'}]
The venison was overcooked but Big Wong's portion size was just right.

In [27]:
gen_data.rename(columns={'generated_text':'raw_text'},inplace=True)

In [28]:
gen_data

,aspect,polarity,prompt,raw_text,aspectTerms
0,[caviar],[Negative],You are a critic who can generate comments on ...,The caviar served at this restaurant was overp...,"[{'term': 'caviar', 'polarity': 'Negative'}]"
1,[vitello alla marsala],[Negative],You are a critic who can generate comments on ...,The vitello alla marsala was a disappointing d...,"[{'term': 'vitello alla marsala', 'polarity': ..."
2,[bar scene],[Positive],You are a critic who can generate comments on ...,The bar scene is always lively and fun to be a...,"[{'term': 'bar scene', 'polarity': 'Positive'}]"
3,[atmoshpere],[Negative],You are a critic who can generate comments on ...,The atmosphere in the restaurant was completel...,"[{'term': 'atmoshpere', 'polarity': 'Negative'}]"
4,[seats],[Positive],You are a critic who can generate comments on ...,The seats were incredibly comfortable and prov...,"[{'term': 'seats', 'polarity': 'Positive'}]"
...,...,...,...,...,...
21495,"[Zucchero Pomodori, bagel, hummus, Leon]","[Negative, Positive, Positive, Neutral]",You are a critic who can generate comments on ...,"The Zucchero Pomodori was a letdown, but the b...","[{'term': 'Zucchero Pomodori', 'polarity': 'Ne..."
21496,"[dosas, Pastis, dining room, chicken vindaloo]","[Positive, Negative, Negative, Positive]",You are a critic who can generate comments on ...,"The dosas were absolutely delicious, but unfor...","[{'term': 'dosas', 'polarity': 'Positive'}, {'..."
21497,"[half/half pizza, lunch buffet, chicken tikka ...","[Neutral, Positive, Positive, Negative]",You are a critic who can generate comments on ...,"The lunch buffet was quite impressive, the chi...","[{'term': 'half/half pizza', 'polarity': 'Neut..."
21498,"[Rao's, fish, lobster sandwich, jukebox]","[Neutral, Positive, Negative, Positive]",You are a critic who can generate comments on ...,The service at Rao's was neutral but the fish ...,"[{'term': 'Rao's', 'polarity': 'Neutral'}, {'t..."
21499,"[meat, fusion twists, BBQ Salmon, sauces]","[Neutral, Negative, Negative, Positive]",You are a critic who can generate comments on ...,"The meat was average, the fusion twists didn't...","[{'term': 'meat', 'polarity': 'Neutral'}, {'te..."

In [29]:
roww = gen_data.iloc[913]
print(roww['raw_text'])
print(roww['aspectTerms'])

The pasta dish was incredibly flavorful with just the right amount of seasoning.
[{'term': 'pasta dish', 'polarity': 'Positive'}]

In [30]:
gen_data['aspectCategories'] = gen_data['aspectTerms'].apply(lambda x: [{'category': 'general', 'polarity': 'neutral'}])

In [31]:
gen_data['sentenceId'] = gen_data.index

In [32]:
gen_data.shape

(21500, 7)

In [33]:
gen_data.to_csv('gen_train_16_20k_format.csv',index=False)